# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerminalTimer < Formula
  desc "A terminal-based timer"
  homepage "https://github.com/cameroncuttingedge/terminal-timer"
  version "0.0.7"

  on_macos do
    on_intel do
      url "https://github.com/cameroncuttingedge/terminal-timer/releases/download/v0.0.7/terminal-timer_0.0.7_darwin_amd64.zip"
      sha256 "31e7ebc0816ff5ce314d98e14e7186fec13c6da3d83df1c9b7c9b978bb1a7812"

      def install
        bin.install "terminal-timer"
      end
    end
    on_arm do
      url "https://github.com/cameroncuttingedge/terminal-timer/releases/download/v0.0.7/terminal-timer_0.0.7_darwin_arm64.zip"
      sha256 "390876693d4dbec00caf28fbc601e27c4668bd01c4d094fa5e1d0b99313cca8c"

      def install
        bin.install "terminal-timer"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cameroncuttingedge/terminal-timer/releases/download/v0.0.7/terminal-timer_0.0.7_linux_amd64.zip"
        sha256 "0ac5f286739d8a37b85173b62024bdfa71a54267ef05d816809c641710c06fc5"

        def install
          bin.install "terminal-timer"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cameroncuttingedge/terminal-timer/releases/download/v0.0.7/terminal-timer_0.0.7_linux_arm64.zip"
        sha256 "d576f589bb6fa0884a294629668c7a255fa3dd95675dba4e75cc657948cb04bf"

        def install
          bin.install "terminal-timer"
        end
      end
    end
  end

  test do
    system "#{bin}/terminal-timer", "--help"
  end
end
